/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfcae.BankAdmin;

import Business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kurki
 */
public class AnalyticsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    
    public AnalyticsJPanel(JPanel userProcessContainer,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business =business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRegionsByTotalDepositAmount = new javax.swing.JButton();
        btnRegionsbyEmployeeCount = new javax.swing.JButton();
        btnRegionsByCustomerCount = new javax.swing.JButton();
        btnRegionsByTotalLoanAmountIssued = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Analytics");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRegionsByTotalDepositAmount.setText(" Regions by Total  Deposit Amount");
        btnRegionsByTotalDepositAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionsByTotalDepositAmountActionPerformed(evt);
            }
        });

        btnRegionsbyEmployeeCount.setText("Regions by Employee Count");
        btnRegionsbyEmployeeCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionsbyEmployeeCountActionPerformed(evt);
            }
        });

        btnRegionsByCustomerCount.setText("Regions by Customer Count");
        btnRegionsByCustomerCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionsByCustomerCountActionPerformed(evt);
            }
        });

        btnRegionsByTotalLoanAmountIssued.setText(" Regions by Total Loan Amount Issued");
        btnRegionsByTotalLoanAmountIssued.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionsByTotalLoanAmountIssuedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRegionsByCustomerCount, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(btnRegionsbyEmployeeCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegionsByTotalLoanAmountIssued, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(btnRegionsByTotalDepositAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(btnRegionsByCustomerCount)
                .addGap(39, 39, 39)
                .addComponent(btnRegionsbyEmployeeCount)
                .addGap(45, 45, 45)
                .addComponent(btnRegionsByTotalDepositAmount)
                .addGap(50, 50, 50)
                .addComponent(btnRegionsByTotalLoanAmountIssued)
                .addGap(115, 115, 115)
                .addComponent(btnBack)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);  
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegionsbyEmployeeCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionsbyEmployeeCountActionPerformed
        RegionsByEmployeeCountJPanel employeeCount = new RegionsByEmployeeCountJPanel(userProcessContainer,business);
        userProcessContainer.add("RegionsByEmployeeCountJPanel",employeeCount);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnRegionsbyEmployeeCountActionPerformed

    private void btnRegionsByCustomerCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionsByCustomerCountActionPerformed
        RegionsByCustomerCountJPanel customerCount = new RegionsByCustomerCountJPanel(userProcessContainer,business);
        userProcessContainer.add("RegionsByCustomerCountJPanel",customerCount);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnRegionsByCustomerCountActionPerformed

    private void btnRegionsByTotalDepositAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionsByTotalDepositAmountActionPerformed
        RegionsByDepositsJPanel deposits = new RegionsByDepositsJPanel(userProcessContainer,business);
        userProcessContainer.add("RegionsByDepositsJPanel",deposits);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnRegionsByTotalDepositAmountActionPerformed

    private void btnRegionsByTotalLoanAmountIssuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionsByTotalLoanAmountIssuedActionPerformed
        RegionsByLoanIssuedJPanel loanIssued = new RegionsByLoanIssuedJPanel(userProcessContainer,business);
        userProcessContainer.add("RegionsByDepositsJPanel",loanIssued);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnRegionsByTotalLoanAmountIssuedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegionsByCustomerCount;
    private javax.swing.JButton btnRegionsByTotalDepositAmount;
    private javax.swing.JButton btnRegionsByTotalLoanAmountIssued;
    private javax.swing.JButton btnRegionsbyEmployeeCount;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
