/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfcae.BankAdmin;

import Business.Business;
import Business.Region.Region;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kurki
 */
public class BankAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAcount;
    private Business business;
    
    public BankAdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAcount,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAcount = userAcount;
        this.business = business;
   
        lblName.setText(String.valueOf(userAcount.getPerson()));
        lblRole.setText(this.userAcount.getRole().getRoleType());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageRegions = new javax.swing.JButton();
        btnManageBillers = new javax.swing.JButton();
        btnAnalytics = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        btnUpdatePersonalProfile = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Welcome ");

        btnManageRegions.setText("Manage Regions");
        btnManageRegions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRegionsActionPerformed(evt);
            }
        });

        btnManageBillers.setText("Manage Billers");
        btnManageBillers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBillersActionPerformed(evt);
            }
        });

        btnAnalytics.setText("Analytics");
        btnAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsActionPerformed(evt);
            }
        });

        btnUpdatePersonalProfile.setText("View Personal Profile");
        btnUpdatePersonalProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePersonalProfileActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblRole.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnManageRegions, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnManageBillers, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnUpdatePersonalProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUser)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRole)
                .addGap(49, 49, 49)
                .addComponent(btnManageRegions)
                .addGap(33, 33, 33)
                .addComponent(btnManageBillers)
                .addGap(32, 32, 32)
                .addComponent(btnAnalytics)
                .addGap(31, 31, 31)
                .addComponent(btnUpdatePersonalProfile)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageRegionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRegionsActionPerformed
        ManageRegionsJPanel manageRegions = new ManageRegionsJPanel(userProcessContainer,business);
        userProcessContainer.add("ManageRegionsJPanel",manageRegions);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnManageRegionsActionPerformed

    private void btnManageBillersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBillersActionPerformed
        ManageBillersJPanel manageBillers = new ManageBillersJPanel(userProcessContainer,business);
        userProcessContainer.add("ManageBillersJPanel",manageBillers);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnManageBillersActionPerformed

    private void btnAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsActionPerformed
        AnalyticsJPanel analytics = new AnalyticsJPanel(userProcessContainer,business);
        userProcessContainer.add("AnalyticsJPanel",analytics);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnalyticsActionPerformed

    private void btnUpdatePersonalProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePersonalProfileActionPerformed
        UpdatePersonProfileBankAdminJPanel updatePersonalProfile = new UpdatePersonProfileBankAdminJPanel(userProcessContainer,userAcount);
        userProcessContainer.add("UpdatePersonProfileBankAdminJPanel",updatePersonalProfile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUpdatePersonalProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnManageBillers;
    private javax.swing.JButton btnManageRegions;
    private javax.swing.JButton btnUpdatePersonalProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
