/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfcae.BankAdmin;

import Business.Business;
import Business.Employee.Employee;
import Business.Region.Region;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kurki
 */
public class ManageRegionsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRegionsJPanel
     */
    
    private JPanel userProcessContainer;
    private Business business;
    
    public ManageRegionsJPanel(JPanel userProcessContainer,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business; 
        populateTable();
       
    }

    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblRegions.getModel();
        dtm.setRowCount(0);
        
        if(!(business.getRegionDirectory().getRegionList().isEmpty()))
        {
            for (Region region : business.getRegionDirectory().getRegionList())
            {
                Object[] row = new Object[2];
                row[0]= region;
                
                ArrayList<Employee> employees = new ArrayList<Employee>();
                employees = region.getEmployeeDirectory().getEmployeeList();
                if(employees.isEmpty())
                {
                    row[1]="";
                }
                else
                {
                    for(Employee e: employees)
                    {
                        row[1] = e;
                    }
                }
                dtm.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegions = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnRemoveRegion = new javax.swing.JButton();
        btnUpdateRegion = new javax.swing.JButton();
        btnNewRegion = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Manage Regions");

        tblRegions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Region Name", "Regional Manager"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRegions);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRemoveRegion.setText("Delete Region");
        btnRemoveRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveRegionActionPerformed(evt);
            }
        });

        btnUpdateRegion.setText("Update Region >>");
        btnUpdateRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRegionActionPerformed(evt);
            }
        });

        btnNewRegion.setText("Create New Region >>");
        btnNewRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRegionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdateRegion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoveRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnNewRegion))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveRegion)
                    .addComponent(btnUpdateRegion)
                    .addComponent(btnNewRegion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRegionActionPerformed
        NewRegionJPanel newRegion = new NewRegionJPanel(userProcessContainer,business);
        userProcessContainer.add("NewRegionJPanel",newRegion);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnNewRegionActionPerformed

    private void btnUpdateRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRegionActionPerformed
      int rowSelected = tblRegions.getSelectedRow();
      
      if (rowSelected < 0)
      {
          JOptionPane.showMessageDialog(null, "Please select a region.","WARNING",JOptionPane.WARNING_MESSAGE);
          return;
      }
      
      Region region = (Region)tblRegions.getValueAt(rowSelected,0);
     
        Employee emp = (Employee)tblRegions.getValueAt(rowSelected, 1);
        UpdateRegionJPanel updateRegion = new UpdateRegionJPanel(userProcessContainer,region,business,emp);
        userProcessContainer.add("UpdateRegionJPanel",updateRegion);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);       
    }//GEN-LAST:event_btnUpdateRegionActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRemoveRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveRegionActionPerformed
      int rowSelected = tblRegions.getSelectedRow();
      
      if (rowSelected < 0)
      {
          JOptionPane.showMessageDialog(null, "Please select a row.","WARNING",JOptionPane.WARNING_MESSAGE);
          return;
      }
      
      Region region = (Region)tblRegions.getValueAt(rowSelected, 0);
      business.getRegionDirectory().removeRegion(region);
      
      JOptionPane.showMessageDialog(null, "Region is deleted successfully.","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
     
      populateTable();
      
    }//GEN-LAST:event_btnRemoveRegionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNewRegion;
    private javax.swing.JButton btnRemoveRegion;
    private javax.swing.JButton btnUpdateRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegions;
    // End of variables declaration//GEN-END:variables
}
