/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LoanEmployee;

import Business.Branch.Branch;
import Business.Department.Department;
import Business.UserAccount.UserAccount;
import UserInterface.RegionalManager.UpdatePersonalProfileJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kurki
 */
public class LoanEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Branch branch;
    private Department department;
    
    public LoanEmployeeWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Branch branch,Department department) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.branch = branch;
        this.department = department;
        
        lblName.setText(String.valueOf(userAccount.getPerson()));
        lblRole.setText(this.userAccount.getRole().getRoleType());
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpenLoanRequests = new javax.swing.JButton();
        btnProcessedByHim = new javax.swing.JButton();
        btnUpdatePersonalProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();

        btnOpenLoanRequests.setText("Open Loan Requests");
        btnOpenLoanRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenLoanRequestsActionPerformed(evt);
            }
        });

        btnProcessedByHim.setText("Loan Requests Processed By Him");
        btnProcessedByHim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessedByHimActionPerformed(evt);
            }
        });

        btnUpdatePersonalProfile.setText("View Personal Profile");
        btnUpdatePersonalProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePersonalProfileActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Welcome ");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblRole.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnProcessedByHim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addComponent(btnOpenLoanRequests, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdatePersonalProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUser)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRole)
                .addGap(62, 62, 62)
                .addComponent(btnOpenLoanRequests)
                .addGap(48, 48, 48)
                .addComponent(btnProcessedByHim)
                .addGap(47, 47, 47)
                .addComponent(btnUpdatePersonalProfile)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenLoanRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenLoanRequestsActionPerformed
        OpenRequestsJPanel openLoanRequests = new OpenRequestsJPanel(userProcessContainer,branch,department,userAccount);
        userProcessContainer.add("OpenRequestsJPanel",openLoanRequests);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnOpenLoanRequestsActionPerformed

    private void btnProcessedByHimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessedByHimActionPerformed
        LoanRequestsProcessedByHim loanRequestsProcessedByHim = new LoanRequestsProcessedByHim(userProcessContainer,branch,department,userAccount);
        userProcessContainer.add("LoanRequestsProcessedByHim",loanRequestsProcessedByHim);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnProcessedByHimActionPerformed

    private void btnUpdatePersonalProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePersonalProfileActionPerformed
        UpdatePersonProfileLoanEmpJPanel updatePersonalProfile = new UpdatePersonProfileLoanEmpJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("UpdatePersonalProfileJPanel",updatePersonalProfile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUpdatePersonalProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenLoanRequests;
    private javax.swing.JButton btnProcessedByHim;
    private javax.swing.JButton btnUpdatePersonalProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
