/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LoanEmployee;

import Business.Branch.Branch;
import Business.Customer.Customer;
import Business.Department.Department;
import Business.Employee.Employee;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LoanWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kurki
 */
public class OpenRequestsJPanel extends javax.swing.JPanel {

   private JPanel userProcessContainer;
   private Branch branch;
   private Department department;
   private UserAccount userAccount;
    
    public OpenRequestsJPanel(JPanel userProcessContainer,Branch branch,Department department,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.branch = branch;
        this.department =department;
        this.userAccount = userAccount;
        populateTable();
        
    }

    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)tblLoan.getModel();
        dtm.setRowCount(0);
   
               if(!department.getWorkQueue().getWorkRequestList().isEmpty())
               {
                    for (WorkRequest w : department.getWorkQueue().getWorkRequestList())
                    {
                        if(w.getStatus().equals("Open") && (w.getReceiver()==null))
                        {
                            if(w instanceof LoanWorkRequest)
                            {
                                if(((LoanWorkRequest) w).getEmployee()==null)
                                {
                                    Object[] row = new Object[5];
                                    row[0]= w;
                                    row[1]= ((LoanWorkRequest) w).getCustomer();
                                    row[2]= ((LoanWorkRequest) w).getCustomeRrequestedLoanAmount();
                                    row[3]= ((LoanWorkRequest) w).getPurpose();
                                    row[4]= w.getStatus();
                                    dtm.addRow(row);
                                }
                            }
                        }
                       
                    }
               }
               
        
        
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssign = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        btnAssign.setText("Assign to Himself");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        tblLoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loan Request ID", "Customer", "Loan Amount", "Purpose", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLoan);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Open Loan Requests");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBack))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAssign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed

        int rowSelected = tblLoan.getSelectedRow();

        if (rowSelected < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row.","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest w = (WorkRequest) tblLoan.getValueAt(rowSelected, 0);
        LoanWorkRequest loanWorkrequest=null;
        Employee emp=null;
        Customer cus = null;
         // Setting the employee in the work request of employee
        if(w instanceof LoanWorkRequest)
        {
             emp = (Employee)userAccount.getPerson();
            ((LoanWorkRequest) w).setEmployee(emp);
             w.setReceiver(userAccount);
             userAccount.getWorkQueue().getWorkRequestList().add((LoanWorkRequest) w); 
            
             loanWorkrequest =(LoanWorkRequest) w;
        }
        
        // Setting the employee in the work request of customer requested
        cus = loanWorkrequest.getCustomer();
        for(UserAccount ua:branch.getUserAccountDirectory().getUserAccountList())
        {
            if(ua.getPerson()==cus)
            {
                for(WorkRequest wr : ua.getWorkQueue().getWorkRequestList())
                {
                    if(wr instanceof LoanWorkRequest)
                    {
                        if(wr==loanWorkrequest)
                        {
                            w.setReceiver(userAccount);
                           ((LoanWorkRequest) wr).setEmployee(emp) ;
                        }
                    }
                }
            }
        }
        
        JOptionPane.showMessageDialog(null, "Work Request is assigned to oneself successfully.","INFORMATION",JOptionPane.INFORMATION_MESSAGE);

        populateTable();

    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLoan;
    // End of variables declaration//GEN-END:variables
}
