/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Biller;

import Business.Account.Account;
import Business.Biller.Biller;
import Business.Business;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kurki
 */
public class OnlineCreditDebit extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Business business;
    private Biller fromBiller;
    private ArrayList<Account> accountList;
    private Boolean isBetweenMyAccounts =false;
    
    public OnlineCreditDebit(JPanel userProcessContainer,UserAccount userAccount,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        
        txtCheckingBalance.setEnabled(false);
        txtSavingsBalance.setEnabled(false);

        
        lblAmount.setVisible(false);
        lblFrom.setVisible(false);
        lblTo.setVisible(false);
        comboFrom.setVisible(false);
        comboTo.setVisible(false);
        txtAmount.setVisible(false);
        btnTransfer.setVisible(false);
        
        // From Biller Accounts
        fromBiller = (Biller)userAccount.getPerson();   
        accountList = fromBiller.getAccountDirectory().getAccountList();
              
        populateAccountBalances();
 
    }

    private void populateAccountBalances()
    {
        
        accountList = fromBiller.getAccountDirectory().getAccountList();
        for(Account a : accountList)
        {
            if(a.getAccountName().equals(Account.AccountType.CheckingAccount.getValue()))
            {
                txtCheckingBalance.setText(String.valueOf(a.getAccountBalance()));
            }
            else if(a.getAccountName().equals(Account.AccountType.SavingsAccount.getValue()))
            {
               txtSavingsBalance.setText(String.valueOf(a.getAccountBalance())); 
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBetweenMyAccounts = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblFrom = new javax.swing.JLabel();
        txtSavingsBalance = new javax.swing.JTextField();
        lblTo = new javax.swing.JLabel();
        txtCheckingBalance = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        comboTo = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        btnTransfer = new javax.swing.JButton();
        comboFrom = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        btnBetweenMyAccounts.setText("Between My Accounts");
        btnBetweenMyAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetweenMyAccountsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Online Credit / Debit");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Amount Transfer");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblFrom.setText("From Account   ");

        lblTo.setText("To Account");

        lblAmount.setText("Amount ");

        comboTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Account Details");

        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        comboFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Checking Account Balance");

        jLabel13.setText("Savings Account Balance");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBetweenMyAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSavingsBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCheckingBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboFrom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAmount)
                                    .addComponent(comboTo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnTransfer)))))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(34, 34, 34))
                            .addComponent(jLabel13))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtCheckingBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31))
                        .addComponent(txtSavingsBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(btnBetweenMyAccounts)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom)
                    .addComponent(comboFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTo)
                    .addComponent(comboTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount))
                .addGap(18, 18, 18)
                .addComponent(btnTransfer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBetweenMyAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetweenMyAccountsActionPerformed

        isBetweenMyAccounts = true;
        lblFrom.setVisible(true);
        lblTo.setVisible(true);
        lblTo.setText("To Account");
        comboFrom.setVisible(true);
        comboTo.setVisible(true);
        lblAmount.setVisible(true);
        txtAmount.setVisible(true);
        btnTransfer.setVisible(true);
        txtAmount.setText("");
        comboFrom.removeAllItems();
        comboTo.removeAllItems();
        for(Account a: accountList )
        {
            comboFrom.addItem(a);
            comboTo.addItem(a);
        }

    }//GEN-LAST:event_btnBetweenMyAccountsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed

        Double amount;

        if (txtAmount.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Amount is mandatory.","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }

        try
        {
            amount = Double.parseDouble(txtAmount.getText().trim());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Amount can only be a numeric value.","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }

        Account from = (Account)comboFrom.getSelectedItem();
        Double balance = from.getAccountBalance();

        if(amount>balance)
        {
            JOptionPane.showMessageDialog(null,"Insufficient Balance","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }

        // BETWEEN MY ACCOUNTS
        if(isBetweenMyAccounts==true)
        {
            Account fromAccount = (Account)comboFrom.getSelectedItem();
            Account toAccount = (Account)comboTo.getSelectedItem();

            if(fromAccount==toAccount)
            {
                JOptionPane.showMessageDialog(null,"From Account and To Account cannot be same.","WARNING",JOptionPane.WARNING_MESSAGE);
                return;
            }

            Double oldAccountBalance;
            //To debit the amount from FromAccount
            for(Account a : accountList)
            {
                if(a==fromAccount)
                {
                    oldAccountBalance= fromAccount.getAccountBalance();
                    a.setAccountBalance(oldAccountBalance - amount);
                }
            }
            //To credit the amount to ToAccount
            for(Account a : accountList)
            {
                if(a==toAccount)
                {
                    oldAccountBalance= toAccount.getAccountBalance();
                    a.setAccountBalance(oldAccountBalance + amount);
                }
            }

        }

      
        JOptionPane.showMessageDialog(null, "Amount Transfer is successful.","INFORMATION",JOptionPane.INFORMATION_MESSAGE);

        isBetweenMyAccounts = false;
        lblFrom.setVisible(false);
        lblTo.setVisible(false);
        comboFrom.setVisible(false);
        comboTo.setVisible(false);
        lblAmount.setVisible(false);
        txtAmount.setVisible(false);
        btnTransfer.setVisible(false);
        populateAccountBalances();

    }//GEN-LAST:event_btnTransferActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBetweenMyAccounts;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JComboBox comboFrom;
    private javax.swing.JComboBox comboTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCheckingBalance;
    private javax.swing.JTextField txtSavingsBalance;
    // End of variables declaration//GEN-END:variables
}
