/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BranchManager;

import Business.Branch.Branch;
import Business.Department.Department;
import Business.Employee.Employee;
import Business.Log;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SecurityWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.SecurityTier2Employee.ProcessedByHimJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kurki
 */
public class SecurityDetailsJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private SecurityWorkRequest securityWorkrequest;
    private Branch branch;
    private Department department;
    private UserAccount userAccount;
    
    public SecurityDetailsJPanel(JPanel userProcessContainer,SecurityWorkRequest securityWorkRequest,Branch branch,Department department,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.securityWorkrequest = securityWorkRequest;
        this.branch = branch;
        this.department = department;
        this.userAccount = userAccount;
        
         btnSave.setEnabled(false);
        if(securityWorkRequest.getStatus().equals("Considered"))
        {
            btnUpdate.setEnabled(false);
        }
        else
        {
            btnUpdate.setEnabled(true);
        }
        
        comboStatus.removeAllItems();
        comboStatus.addItem("Notify Manager");

        txtResolvedDate.setEnabled(false);
        txtID.setText(String.valueOf(securityWorkRequest.getSecurityWorkRequestID()));
        txtEmployee.setText(securityWorkRequest.getSender().getPerson().toString());
        if(securityWorkRequest.getMessage()==null)
        {
            txtMessage.setText("");
        }
        else
        {
        txtMessage.setText(String.valueOf(securityWorkRequest.getMessage()));
        }
        txtRequestedDate.setText(String.valueOf(securityWorkRequest.getRequestDate()));
        txtResolvedDate.setText(String.valueOf(securityWorkRequest.getResolveDate()));
        comboStatus.setSelectedItem(securityWorkRequest.getStatus());
        txtSuggestions.setText(securityWorkRequest.getSuggestions());
        
        btnSave.setEnabled(false);
        txtMessage.setEnabled(false);
        comboStatus.setEnabled(false);
        txtEmployee.setEnabled(false);
        txtEmployee.setEnabled(false);
        txtID.setEnabled(false);
        txtMessage.setEnabled(false);
        txtSuggestions.setEnabled(false);
        txtRequestedDate.setEnabled(false);  
        
        populatTable();
    }
    
    public void populatTable()
    {

        DefaultTableModel dtm = (DefaultTableModel) tblDetails.getModel();
        dtm.setRowCount(0);
          
            for (Log log : (securityWorkrequest.getLogDirectory().getLogList()))
            {
                    Object[] row = new Object[5];
                    row[0]= log;
                    row[1] =log.getRole();
                    row[2] =log.getIPAddress();
                    row[3] =log.getTime();
                    row[4] =log.getMessage();
                    dtm.addRow(row);
            }
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtRequestedDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox<>();
        txtEmployee = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtResolvedDate = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSuggestions = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Message");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 75, 116, -1));
        add(txtRequestedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 134, 242, -1));

        jLabel6.setText("Status");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 106, 116, -1));

        jLabel7.setText("Requested Date");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 137, 116, -1));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 72, 280, -1));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 103, 280, -1));
        add(txtEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 103, 244, -1));

        jLabel8.setText("Resolved  Date");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 168, 116, -1));
        add(txtResolvedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 165, 242, -1));
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 72, 244, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("View Security Request Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 236, -1));

        jLabel4.setText("Suggested Solutions");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 137, 127, -1));
        add(txtSuggestions, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 134, 280, -1));

        jLabel2.setText("Security Request ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 75, 126, -1));

        jLabel3.setText("Employee Requested");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 106, 126, -1));

        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role", "IP Address", "Time", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDetails);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 203, 800, 177));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 425, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 425, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 497, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        btnSave.setEnabled(true);
        txtMessage.setEnabled(true);
        comboStatus.setEnabled(true);
        comboStatus.removeAllItems();
        comboStatus.addItem("Considered");
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        
        // Setting the status of security request in the work queue of officer requested
        Employee emp =(Employee)securityWorkrequest.getSender().getPerson();

        for(UserAccount ua:department.getUserAccountDirectory().getUserAccountList())
        {
            if(ua.getPerson()==emp)
            {
                for(WorkRequest w : ua.getWorkQueue().getWorkRequestList())
                {
                    if(w instanceof SecurityWorkRequest)
                    {
                        if(w==securityWorkrequest)
                        {
                            w.setStatus((String)comboStatus.getSelectedItem());
                            w.setMessage(txtMessage.getText().trim());
                        }
                    }
                }
            }
        }

        // Setting the status of security request in the work queue of  Receiver(Employee Processed)

        Employee employee =(Employee)securityWorkrequest.getReceiver().getPerson();

        for(UserAccount ua:department.getUserAccountDirectory().getUserAccountList())
        {
            if(ua.getPerson()==employee)
            {
                for(WorkRequest w : ua.getWorkQueue().getWorkRequestList())
                {
                    if(w instanceof SecurityWorkRequest)
                    {
                        if(w==securityWorkrequest)
                        {
                            w.setStatus((String)comboStatus.getSelectedItem());
                            w.setMessage(txtMessage.getText().trim());
                        }
                    }
                }
            }
        }

        // Setting the status in Branch's Loan Department's WorkQueue
        for(Department d:branch.getDepartmentDirectory().getDepartmentList())
        {
            if(d.getDepartmentName().equals(Department.DepartmentType.LoanDepartment.getValue()))
            {
                for(WorkRequest w :d.getWorkQueue().getWorkRequestList())
                {
                    if(w instanceof SecurityWorkRequest)
                    {
                        if(w==securityWorkrequest)
                        {
                            w.setStatus((String)comboStatus.getSelectedItem());
                            w.setMessage(txtMessage.getText().trim());
                        }
                    }
                }

            }
        }
        
        JOptionPane.showMessageDialog(null, "Security Request is considered successfully.","INFORMATION",JOptionPane.INFORMATION_MESSAGE);

        btnSave.setEnabled(false);
        txtMessage.setEnabled(false);;
        comboStatus.setEnabled(false);
        btnUpdate.setEnabled(false);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SecurityRequestsJPanel requestsByHim = (SecurityRequestsJPanel) component;
        requestsByHim.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDetails;
    private javax.swing.JTextField txtEmployee;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtRequestedDate;
    private javax.swing.JTextField txtResolvedDate;
    private javax.swing.JTextField txtSuggestions;
    // End of variables declaration//GEN-END:variables
}
